farshadz1997/Microsoft-Rewards-bot

.gitignore, ms_rewards_farmer.py
Also added the Profiles directory to the .gitignore after the headache I caused myself by accidentally committing it earlier (see my previous aborted PRs)!
=> Adding an optional CLI parameter to make the script autoexit after it completes

README.md, setup.md
=> Create setup.md REFERENCE: #146

.deepsource.toml, README.md, ms_rewards_farmer.py, setup.md
NOTE: `--autoredeem` is fully developed by @dmarts05, all I did was add merge the feature into my branch, which consisted of clicking ctrl+c and ctrl+v lol. 
This pull brings `--calculator`, `--superfast`, and `--autoredeem`. --superfast is at least 50% faster than --fast, and in some cases up to 1200% faster than normal speed. --calculator is a tkinter based calculator based on my github repository https://github.com/Prabh-Saini/msrewardsestimator, activated by using `--calculator` which prevents the script from running and opens the window below. I've added the appropriate information in readme.md and added calculator.bat in setup.md. The UI uses tkinter therefore it should run well on macOS, Windows, and Linux. on all CPU architectures including raspberry pi (armv8). Meaning there is …
=> --calculator, --superfast, and --redeem (CREDITS:  dmarts05)

ms_rewards_farmer.py
Tested on Pop_OS! 22.04 LTS, works fine.
=> main: Add shutdown for linux systems

ms_rewards_farmer.py
IMPORTANT --REDEEM CHECK ADDED TO createMessage()
FIXES #171
Without this bug fix and not running --redeem, it will create an error and not send a discord/telegram message. and also disturb --everyday in the script
=> [URGENT] #171 FIX

README.md, ms_rewards_farmer.py, setup.md
This makes set up much easier and also doesn't interrupt the script running especially when a newer version of chrome is installed and the is not up to date.
FIXES #140
=> Automatic webdriver installer

README.md, ms_rewards_farmer.py
**Improved currency feature:**
● Users can now choose from multiple currency options: EUR, USD, AUD, INR, GBP, CAD, JPY, CHF, NZD, ZAR, BRL, CNY, HKD, SGD, THB
● Currency can be selected at the beginning using the --currency flag 
● Overall, this change makes the message more organized and easier to understand 
**Example:**
python ms_rewards_farmer.py --currency EUR
=> Added --currency

README.md
quick hotfix @farshadz1997 push it in to master whenever you can
=> Update README.md with --virtual-display

searchwords.txt
=> Added more search terms (thanks chatgpt)

README.md, setup.md
=> Updated setup.md to accommodate Linux users

README.md, exceptions.py, ms_rewards_farmer.py, requirements.txt
This makes it possible to use the bot on 2FA protected accounts by (optionally) providing the TOTP secret in the _accounts.json_ file.
The bot will automatically generate a TOTP code if it detects the 2FA screen using [pyotp](https://github.com/pyauth/pyotp).
=> Added TOTP support using pyotp

ms_rewards_farmer.py
Set larger window size if headless mode on linux system before msn game to avoid 'not interctable errors'
=> Set larger window size for msn game

ms_rewards_farmer.py
Changed get_version(), adding absolute version.json path to avoid unknown version error
=> Updated get_version()

ms_rewards_farmer.py
This will click "Start Earning Points" in the welcome page, and will answer the first quiz, then close the page. 
in answer to https://github.com/farshadz1997/Microsoft-Rewards-bot/issues/220
=> Pass the welcome page.

ms_rewards_farmer.py
further Fixes #208 
check for update if its running 24/7.
=> don't prompt for update if virtual display and check for update everyday

README.md, ms_rewards_farmer.py, setup.md
i'm using proxies in my Linux device and sometimes it reports live proxies as dead, it happens to me daily and i have to run the bot again. so i came up with a solution to recheck proxies.
=> Added option to recheck proxy and added guidelines to run bot on ARM Linux devices

README.md, ms_rewards_farmer.py
its one of the most important flag as for me. 
its useful when you are using a VPS. and don't want to go all the way to vps ssh and check if its working or not. hooking into program std. its a lot hectic
specially when you have it setup to run automatically on cron job.
=> addition of --send-to-webhook flag.

ms_rewards_farmer.py
MSN Shopping Game never worked for me when farming with my Raspberry Pi in headless mode or when using virtual-display.
Adding `options.add_argument("--window-size=1920,1080")` fixes the problem for me.
=> Fix MSN Shopping Game for headless mode and virtual display

run.sh, setup.md
Hello there,
I have added a shell script to run the Python bot easily on a Linux machine. This should make it simpler for users to deploy and utilize the bot. Please review and consider merging this pull request into the main repository.
Thank you for your time and consideration.
Best regards, Abhinav
=> Added shell script for linux

run.sh
Since most of the time the script needs to be updated, I have added the update script in the same shell file so that users can save a little bit of their time. If an update is available, uses will just press 'y'. Else the program would execute as it is.
=> Enable users to update the script on the go.

ms_rewards_farmer.py
Makes --account-browser use the account's corresponding proxy.
=> Make account browser use proxy

ms_rewards_farmer.py, requirements.txt
Just for better safety, as suggested by someone in discord.
=> Use selenium-stealth

README.md
Added a very short explanation of how to use this function
=> added more info for the telegram command

README.md, ms_rewards_farmer.py
=> Add support for proxy authentication
